# ===============================
# Application
# ===============================
spring.application.name=inquiry-management
server.port=8080

# ===============================
# MySQL Database
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/inquiry_management?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
spring.datasource.username=root
spring.datasource.password=Sham@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# JWT Configuration
# ===============================
app.jwt.expiration=86400000
app.jwt.secret=awdeftbjpoeabcuebkbbcyiavgjciboiboaibivcibidcnisdab

# ===============================
# Admin Credentials
# ===============================
app.admin.username=admin
app.admin.password=pass@123
app.admin.email=admin@linkcode.in

# ===============================
# Mail Configuration
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shambharaskar9766@gmail.com
spring.mail.password=hwxp hqra cogt edkh

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

